services:
  analytics:
    build:
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - anal-network
    volumes:
      - ../.env:/.env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy