{
 "title": "Drone Analytics Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Средняя дистанция полета",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    { "expr": "drone_avg_distance_meters", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Общая дистанция полета",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    { "expr": "drone_total_distance_meters", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Макс. время полета",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "drone_max_flight_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Макс. скорость",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "drone_max_speed_mps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Кол-во полетов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "drone_total_flights", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Макс. дистанция",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "drone_max_distance_meters", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ср. расход батареи",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "drone_avg_battery_drain_percent",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}